### ISSUE TITLE
[Task] Chat_채팅 차단,  목록 조회, 채팅방 내용 조회

### ISSUE THREAD

**Issue by iysh321** [codestates/Yeollin-Jib#21]
### ISSUE
* Group: server

### TODO
- [ ] Job1  채팅 차단
- [ ] Job2 채팅방 내용 조회
- [ ] Job3 목록 조회

### Estimated time
Pick one
```3h```
